# Site settings
title: It's me, Andrew
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://andrewhage.com" # the base hostname & protocol for your site

ethereum: andrewhage.eth
github_username: andrewhage

# Build settings
markdown: kramdown
